const mockContacts = [
  { id: 18, first_name: "Vanya", last_name: "Patel", email: "vanya.patel@example.com", phone: "+919876543211", company: "TCS", job_title: "HR Manager" },
  { id: 19, first_name: "Ishaan", last_name: "Verma", email: "ishaan.verma@example.com", phone: "+919876543212", company: "Wipro", job_title: "Data Scientist" },
  { id: 20, first_name: "Diya", last_name: "Reddy", email: "diya.reddy@example.com", phone: "+919876543213", company: "HCL", job_title: "Project Manager" },
  { id: 21, first_name: "Arjun", last_name: "Singh", email: "arjun.singh@example.com", phone: "+919876543214", company: "Accenture", job_title: "Business Analyst" },
  { id: 22, first_name: "Maya", last_name: "Gupta", email: "maya.gupta@example.com", phone: "+919876543215", company: "Tech Mahindra", job_title: "Software Developer" },
  { id: 23, first_name: "Kabir", last_name: "Kumar", email: "kabir.kumar@example.com", phone: "+919876543216", company: "Cognizant", job_title: "UI/UX Designer" },
  { id: 24, first_name: "Ananya", last_name: "Shukla", email: "ananya.shukla@example.com", phone: "+919876543217", company: "HDFC Bank", job_title: "Financial Analyst" },
  { id: 25, first_name: "Rohan", last_name: "Mehta", email: "rohan.mehta@example.com", phone: "+919876543218", company: "ICICI Bank", job_title: "Operations Manager" },
  { id: 26, first_name: "Saanvi", last_name: "Nair", email: "saanvi.nair@example.com", phone: "+919876543219", company: "Tata Steel", job_title: "Quality Assurance" },
  { id: 27, first_name: "Raj", last_name: "Bhatia", email: "raj.bhatia@example.com", phone: "+919876543220", company: "TCS", job_title: "Cloud Architect" },
  { id: 28, first_name: "Simran", last_name: "Joshi", email: "simran.joshi@example.com", phone: "+919876543221", company: "Oracle", job_title: "DevOps Engineer" },
  { id: 29, first_name: "Ayaan", last_name: "Gupta", email: "ayaan.gupta@example.com", phone: "+919876543222", company: "Samsung", job_title: "Marketing Executive" },
  { id: 30, first_name: "Sia", last_name: "Chopra", email: "sia.chopra@example.com", phone: "+919876543223", company: "Airtel", job_title: "Network Engineer" },
  { id: 31, first_name: "Avi", last_name: "Bansal", email: "avi.bansal@example.com", phone: "+919876543224", company: "Reliance Jio", job_title: "Product Manager" },
  { id: 32, first_name: "Shruti", last_name: "Kaur", email: "shruti.kaur@example.com", phone: "+919876543225", company: "L&T", job_title: "Electrical Engineer" },
  { id: 33, first_name: "Karan", last_name: "Patel", email: "karan.patel@example.com", phone: "+919876543226", company: "Google", job_title: "Software Engineer" },
  { id: 34, first_name: "Neha", last_name: "Sethi", email: "neha.sethi@example.com", phone: "+919876543227", company: "Amazon", job_title: "HR Specialist" },
  { id: 35, first_name: "Manav", last_name: "Verma", email: "manav.verma@example.com", phone: "+919876543228", company: "Hindustan Unilever", job_title: "Marketing Manager" },
  { id: 36, first_name: "Khushboo", last_name: "Sharma", email: "khushboo.sharma@example.com", phone: "+919876543229", company: "Infosys", job_title: "Project Coordinator" },
  { id: 37, first_name: "Ankit", last_name: "Rajput", email: "ankit.rajput@example.com", phone: "+919876543230", company: "Capgemini", job_title: "Business Analyst" },
  { id: 38, first_name: "Meera", last_name: "Iyer", email: "meera.iyer@example.com", phone: "+919876543231", company: "Cognizant", job_title: "Software Architect" },
  { id: 39, first_name: "Nikhil", last_name: "Rathore", email: "nikhil.rathore@example.com", phone: "+919876543232", company: "Wipro", job_title: "Database Administrator" },
  { id: 40, first_name: "Priya", last_name: "Reddy", email: "priya.reddy@example.com", phone: "+919876543233", company: "HCL", job_title: "Cloud Specialist" },
  { id: 41, first_name: "Vishal", last_name: "Kumar", email: "vishal.kumar@example.com", phone: "+919876543234", company: "Tech Mahindra", job_title: "Business Development" },
  { id: 74, first_name: "Anushka", last_name: "Srivastava", email: "sri.anushka03@gmail.com", phone: "+917026179621", company: "Freelancer", job_title: "Student" },
];

export default mockContacts;
